import 'package:flutter/material.dart';

const List<String> allCategoryIcons = [
  'account_balance_wallet', 'savings', 'credit_card', 'payments', 'wallet', 'money',
  'restaurant', 'directions_car', 'shopping_bag', 'bolt', 'local_activity',
  'local_hospital', 'school', 'code', 'trending_up', 'home',
  'card_giftcard', 'more_horiz', 'flight_takeoff', 'shopping_cart',
  'favorite', 'pets', 'devices', 'fitness_center', 'book',
  'work', 'celebration', 'construction', 'eco', 'flight',
  'grass', 'icecream', 'kitchen', 'landscape', 'medical_services',
  'nature', 'park', 'photo_camera', 'power', 'public',
  'recycling', 'restaurant_menu', 'security', 'self_improvement',
  'smartphone', 'solar_power', 'spa', 'sports_esports',
  'star', 'sunny', 'theater_comedy', 'timer',
  'toys', 'train', 'two_wheeler',
  'verified', 'water_drop', 'web', 'weekend',
  'yard',
];

IconData iconDataFromString(String name) {
  const icons = {
    'account_balance_wallet': Icons.account_balance_wallet,
    'savings': Icons.savings,
    'credit_card': Icons.credit_card,
    'payments': Icons.payments,
    'wallet': Icons.wallet,
    'money': Icons.money,
    'restaurant': Icons.restaurant,
    'directions_car': Icons.directions_car,
    'shopping_bag': Icons.shopping_bag,
    'bolt': Icons.bolt,
    'local_activity': Icons.local_activity,
    'local_hospital': Icons.local_hospital,
    'school': Icons.school,
    'code': Icons.code,
    'trending_up': Icons.trending_up,
    'home': Icons.home,
    'card_giftcard': Icons.card_giftcard,
    'more_horiz': Icons.more_horiz,
    'flight_takeoff': Icons.flight_takeoff,
    'shopping_cart': Icons.shopping_cart,
    'favorite': Icons.favorite,
    'pets': Icons.pets,
    'devices': Icons.devices,
    'fitness_center': Icons.fitness_center,
    'book': Icons.book,
    'work': Icons.work,
    'celebration': Icons.celebration,
    'construction': Icons.construction,
    'eco': Icons.eco,
    'flight': Icons.flight,
    'grass': Icons.grass,
    'icecream': Icons.icecream,
    'kitchen': Icons.kitchen,
    'landscape': Icons.landscape,
    'medical_services': Icons.medical_services,
    'nature': Icons.nature,
    'park': Icons.park,
    'photo_camera': Icons.photo_camera,
    'power': Icons.power,
    'public': Icons.public,
    'recycling': Icons.recycling,
    'restaurant_menu': Icons.restaurant_menu,
    'security': Icons.security,
    'self_improvement': Icons.self_improvement,
    'smartphone': Icons.smartphone,
    'solar_power': Icons.solar_power,
    'spa': Icons.spa,
    'sports_esports': Icons.sports_esports,
    'star': Icons.star,
    'sunny': Icons.sunny,
    'theater_comedy': Icons.theater_comedy,
    'timer': Icons.timer,
    'toys': Icons.toys,
    'train': Icons.train,
    'two_wheeler': Icons.two_wheeler,
    'verified': Icons.verified,
    'water_drop': Icons.water_drop,
    'web': Icons.web,
    'weekend': Icons.weekend,
    'yard': Icons.yard,
  };
  return icons[name] ?? Icons.account_balance_wallet;
}

Color colorFromHex(String hex) {
  hex = hex.replaceFirst('0xFF', '').replaceFirst('#', '');
  return Color(int.parse('FF$hex', radix: 16));
}
